# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, 
# values which you are expected to set up once and rarely edit after 
# that. If you find yourself editing these this file very often, 
# consider using Jekyll's data files feature for the data you need to 
# update frequently.

# For technical reasons, this file is *NOT* reloaded automatically when 
# you use 'jekyll serve'. If you change this file, please restart the
# server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML 
# files, you will see them accessed via {{ site.title }}, 
# {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be 
# accessible in the templates via {{ site.myvariable }}.

# Site settings
title: Nicolás Navarro-Guerrero
email: nicolas.navarro.guerrero@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal website of Nicolás Navarro-Guerrero. 
  Areas of interest and specialties robotics, embedded systems and automation.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nicolas-navarro-guerrero.github.io" # the base hostname & protocol for your site

brand: Nicolás Navarro-Guerrero

#twitter_username: jekyllrb
github_username:  nicolas-navarro-guerrero

# Build settings
markdown: kramdown

future: true
excerpt_separator: <!--more-->

permalink: pretty

collections:
- publications
- pub-collaborations
- courses
- supervised-theses
- videos


defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "fullwidth"
      author: "Nicolas Navarro-Guerrero"
  - scope:
      path: "assets/img"
    values:
      image: true

  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "fullwidth"
      author: "Nicolas Navarro-Guerrero"
  - scope:
      path: "assets/img"
    values:
      image: true

