# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nicolás Navarro-Guerrero
email: nicolas.navarro.guerrero@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal website of Nicolás Navarro-Guerrero. 
  Areas of interest and specialties robotics, embedded systems and automation.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nicolas-navarro-guerrero.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  nicolas-navarro-guerrero

# Build settings
markdown: kramdown

excerpt_separator: <!--more-->

collections:
- publications
- pub-collaborations
- courses
- supervised-theses
- videos
